// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UykusuzPenApi.Data;

#nullable disable

namespace UykusuzPenApi.Migrations
{
    [DbContext(typeof(UykusuzPenDbContext))]
    [Migration("20251002191822_AddKategoriIdToRenkler")]
    partial class AddKategoriIdToRenkler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UykusuzPenApi.Models.Galeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Il")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Ilce")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KapakResmi")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("MedyaTipi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MedyaYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("galeri", (string)null);
                });

            modelBuilder.Entity("UykusuzPenApi.Models.IletisimMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("IsTuru")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("iletisim_mesajlari", (string)null);
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext")
                        .HasColumnName("aciklama");

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("kategori_adi");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("slug");

                    b.Property<int?>("UstKategoriId")
                        .HasColumnType("int")
                        .HasColumnName("ust_kategori_id");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UstKategoriId");

                    b.ToTable("kategoriler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "PVC pencere sistemleri",
                            KategoriAdi = "PVC Pencere",
                            Slug = "pvc-pencere"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "PVC kapı sistemleri",
                            KategoriAdi = "PVC Kapı",
                            Slug = "pvc-kapi"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "Cam balkon sistemleri",
                            KategoriAdi = "Cam Balkon",
                            Slug = "cam-balkon"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Pergola sistemleri",
                            KategoriAdi = "Pergola",
                            Slug = "pergola"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "Tek camlı PVC pencereler",
                            KategoriAdi = "Tek Cam",
                            Slug = "tek-cam",
                            UstKategoriId = 1
                        },
                        new
                        {
                            Id = 6,
                            Aciklama = "Çift camlı PVC pencereler",
                            KategoriAdi = "Çift Cam",
                            Slug = "cift-cam",
                            UstKategoriId = 1
                        });
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.ToTable("kullanicilar", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdSoyad = "Yönetici",
                            Email = "admin@uykusuzpen.com",
                            KullaniciAdi = "admin",
                            Sifre = "$2a$11$XmGE3nQrLsYhK4Z9qY5lIe9HqE.RJxDNZMxRvXLJB7K/7r5nZ8xNi"
                        });
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Renk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int")
                        .HasColumnName("kategori_id");

                    b.Property<string>("RenkAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("RenkAdi")
                        .IsUnique();

                    b.ToTable("renkler", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RenkAdi = "Beyaz"
                        },
                        new
                        {
                            Id = 2,
                            RenkAdi = "Krem"
                        },
                        new
                        {
                            Id = 3,
                            RenkAdi = "Antrasit Gri"
                        },
                        new
                        {
                            Id = 4,
                            RenkAdi = "Füme"
                        },
                        new
                        {
                            Id = 5,
                            RenkAdi = "Kahverengi"
                        },
                        new
                        {
                            Id = 6,
                            RenkAdi = "Meşe Desenli"
                        },
                        new
                        {
                            Id = 7,
                            RenkAdi = "Ceviz Desenli"
                        },
                        new
                        {
                            Id = 8,
                            RenkAdi = "Altın Meşe"
                        },
                        new
                        {
                            Id = 9,
                            RenkAdi = "Winchester"
                        },
                        new
                        {
                            Id = 10,
                            RenkAdi = "Maun"
                        });
                });

            modelBuilder.Entity("UykusuzPenApi.Models.SeoAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MetaDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("MetaKeywords")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("SayfaId")
                        .HasColumnType("int");

                    b.Property<string>("SayfaTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SayfaTipi", "SayfaId")
                        .IsUnique();

                    b.ToTable("seo_ayarlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MetaDescription = "İstanbul'un en kaliteli PVC pencere, kapı ve cam balkon sistemleri. Uygun fiyat, hızlı montaj.",
                            MetaKeywords = "uykusuzpen, pvc pencere, pvc kapı, cam balkon, pergola, İstanbul",
                            SayfaTipi = "anasayfa",
                            Title = "UykusuzPen - PVC Pencere ve Kapı Sistemleri | Kaliteli ve Uygun Fiyat"
                        });
                });

            modelBuilder.Entity("UykusuzPenApi.Models.SiteAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AyarAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AyarDegeri")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AyarAdi")
                        .IsUnique();

                    b.ToTable("site_ayarlari", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Site ana başlığı",
                            AyarAdi = "site_baslik",
                            AyarDegeri = "UykusuzPen - PVC Sistemleri"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "İletişim telefonu",
                            AyarAdi = "telefon",
                            AyarDegeri = "+90 (212) XXX XX XX"
                        },
                        new
                        {
                            Id = 3,
                            Aciklama = "İletişim e-postası",
                            AyarAdi = "email",
                            AyarDegeri = "info@uykusuzpen.com"
                        },
                        new
                        {
                            Id = 4,
                            Aciklama = "Firma adresi",
                            AyarAdi = "adres",
                            AyarDegeri = "İstanbul, Türkiye"
                        },
                        new
                        {
                            Id = 5,
                            Aciklama = "WhatsApp numarası",
                            AyarAdi = "whatsapp",
                            AyarDegeri = "+90 5XX XXX XX XX"
                        });
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Urun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("longtext");

                    b.Property<string>("AnaResim")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("int");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("urunler", (string)null);
                });

            modelBuilder.Entity("UykusuzPenApi.Models.UrunRenk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RenkId")
                        .HasColumnType("int")
                        .HasColumnName("renk_id");

                    b.Property<int>("UrunId")
                        .HasColumnType("int")
                        .HasColumnName("urun_id");

                    b.HasKey("Id");

                    b.HasIndex("RenkId");

                    b.HasIndex("UrunId", "RenkId")
                        .IsUnique();

                    b.ToTable("urun_renkler", (string)null);
                });

            modelBuilder.Entity("UykusuzPenApi.Models.UrunResim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ResimYolu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("urun_resimleri", (string)null);
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Galeri", b =>
                {
                    b.HasOne("UykusuzPenApi.Models.Kategori", "Kategori")
                        .WithMany("Galeriler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Kategori", b =>
                {
                    b.HasOne("UykusuzPenApi.Models.Kategori", "UstKategori")
                        .WithMany("AltKategoriler")
                        .HasForeignKey("UstKategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UstKategori");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Renk", b =>
                {
                    b.HasOne("UykusuzPenApi.Models.Kategori", "Kategori")
                        .WithMany()
                        .HasForeignKey("KategoriId");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Urun", b =>
                {
                    b.HasOne("UykusuzPenApi.Models.Kategori", "Kategori")
                        .WithMany("Urunler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.UrunRenk", b =>
                {
                    b.HasOne("UykusuzPenApi.Models.Renk", "Renk")
                        .WithMany("UrunRenkler")
                        .HasForeignKey("RenkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UykusuzPenApi.Models.Urun", "Urun")
                        .WithMany("UrunRenkler")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Renk");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.UrunResim", b =>
                {
                    b.HasOne("UykusuzPenApi.Models.Urun", "Urun")
                        .WithMany("UrunResimleri")
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Kategori", b =>
                {
                    b.Navigation("AltKategoriler");

                    b.Navigation("Galeriler");

                    b.Navigation("Urunler");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Renk", b =>
                {
                    b.Navigation("UrunRenkler");
                });

            modelBuilder.Entity("UykusuzPenApi.Models.Urun", b =>
                {
                    b.Navigation("UrunRenkler");

                    b.Navigation("UrunResimleri");
                });
#pragma warning restore 612, 618
        }
    }
}
